package edu.floridapoly.mobiledeviceapps.spring20.getoutofit.data;

import androidx.room.Embedded;
import androidx.room.Entity;
import androidx.room.Ignore;
import androidx.room.PrimaryKey;

import java.util.Date;

@Entity(tableName = "text_alarms")
public class TextAlarmEntry {
    @PrimaryKey(autoGenerate = true)
    private int alarmId;
    private Date dateTime;
    private String senderInfo;
    @Embedded
    private MessageDataEntry messageData;

    @Ignore
    public TextAlarmEntry(Date dateTime, String senderInfo, MessageDataEntry messageData) {
        this.dateTime = dateTime;
        this.senderInfo = senderInfo;
        this.messageData = messageData;
    }

    /**
     * Constructor should only be used by room to obtain an object from the DB
     *
     * @param alarmId     The autogenerated id of the alarm
     * @param dateTime    The user selected time and date in 1 Date object
     * @param senderInfo  The information regarding who the 'sender' should be
     * @param messageData The data relating to the message to be sent.
     */
    public TextAlarmEntry(int alarmId, Date dateTime, String senderInfo, MessageDataEntry messageData) {
        this.alarmId = alarmId;
        this.dateTime = dateTime;
        this.senderInfo = senderInfo;
        this.messageData = messageData;
    }

    public int getAlarmId() {
        return alarmId;
    }

    public void setAlarmId(int alarmId) {
        this.alarmId = alarmId;
    }

    public Date getDateTime() {
        return dateTime;
    }

    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }

    public String getSenderInfo() {
        return senderInfo;
    }

    public void setSenderInfo(String senderInfo) {
        this.senderInfo = senderInfo;
    }

    public MessageDataEntry getMessageData() {
        return messageData;
    }

    public void setMessageData(MessageDataEntry messageData) {
        this.messageData = messageData;
    }
}
